# Dev environment compose file

version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"

  hasura:
    build: packages/hasura
    env_file: packages/hasura/.env
    ports:
      - "8080:8080"

  backend:
    build: packages/backend
    ports:
      - "3000:3000"

  frontend:
    build: packages/frontend
    env_file: packages/frontend/.env
    ports:
      - "80:80"

volumes:
  db_data:

