-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."onboarding_requests" add column "confirmed" boolean
--  not null default '0';
