global:
  pgUser: secretariat
  pgDatabase: secretariat

app:
  vars:
    ENV: review

cnpg-cluster:
  ~chart: pg
  ~preDeploy.cleaner:
    match:
      kind: Cluster
    value: true
  cnpg-cluster:
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "cnpg-cluster-db"
      targetTime: "2023-09-06T09:00:00"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://secretariat-prod-backups/secretariat"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "secretariat-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "secretariat-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "secretariat-prod-backups-access-key"
            key: bucket_region
