# hasura:
#   ~needs: [create-db]

# jobs:
#   runs:
#     create-db:
#       use: create-db

deactivate:
  enabled: false
  jobs-deactivate:
    runs:
      deactivate:
        with:
          db: true
