app:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 1024Mi
  autoscale:
    enabled: true
    minReplicas: 2

hasura:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 1024Mi
  autoscale:
    enabled: true
    minReplicas: 2

