app:
  labels:
    oblik.socialgouv.io/enabled: "true"
  annotations:
    oblik.socialgouv.io/increase-request-cpu-algo: "ratio"
    oblik.socialgouv.io/increase-request-cpu-value: "0.1"
    oblik.socialgouv.io/increase-request-memory-algo: "ratio"
    oblik.socialgouv.io/increase-request-memory-value: "0.1"
  vars:
    ENV: prod
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 256Mi
  #   limits:
  #     cpu: 200m
  #     memory: 386Mi
  autoscale:
    enabled: true

hasura:
  labels:
    oblik.socialgouv.io/enabled: "true"
  annotations:
    oblik.socialgouv.io/increase-request-cpu-algo: "ratio"
    oblik.socialgouv.io/increase-request-cpu-value: "0.1"
    oblik.socialgouv.io/increase-request-memory-algo: "ratio"
    oblik.socialgouv.io/increase-request-memory-value: "0.1"
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 512Mi
  #   limits:
  #     cpu: 200m
  #     memory: 1Gi
  autoscale:
    enabled: true

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "82"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
