app:
  vars:
    ENV: prod
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 200Mi
  #   limits:
  #     cpu: 30m
  #     memory: 400Mi
  autoscale:
    enabled: true
    minReplicas: 2

hasura:
  # resources:
  #   requests:
  #     cpu: 50m
  #     memory: 512Mi
  #   limits:
  #     cpu: 100m
  #     memory: 1024Mi
  autoscale:
    enabled: true
    minReplicas: 2

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_HASURA_URL: "https://hasura-{{ .Values.global.host }}/v1/graphql"
          NEXT_PUBLIC_MATOMO_SITE_ID: "82"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
