app:
  resources:
    requests:
      cpu: 15m
      memory: 200Mi
    limits:
      cpu: 30m
      memory: 400Mi
  autoscale:
    enabled: true
    minReplicas: 2

hasura:
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 100m
      memory: 1024Mi
  autoscale:
    enabled: true
    minReplicas: 2

