app:
  vars:
    ENV: prod
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 386Mi
  autoscale:
    enabled: true

hasura:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1Gi
  autoscale:
    enabled: true

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "82"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
