app:
  vars:
    ENV: prod
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      cpu: 100m
      memory: 1Gi
  autoscale:
    enabled: true

hasura:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  autoscale:
    enabled: true

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "82"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
