app:
  vars:
    ENV: prod
  resources:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      cpu: 100m
      memory: 1Gi
  autoscale:
    enabled: true
    minReplicas: 2

hasura:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  autoscale:
    enabled: true
    minReplicas: 2

pg:
  ~chart: pg
  cnpg-cluster:
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://secretariat-prod-backups/secretariat"
        ~tpl~serverName: cnpg-cluster
        s3Credentials:
          accessKeyId:
            ~tpl~name: "secretariat-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "secretariat-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "secretariat-prod-backups-access-key"
            key: bucket_region

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildArgs:
          NEXT_PUBLIC_MATOMO_SITE_ID: "82"
          NEXT_PUBLIC_MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
