# Dev environment compose file

version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    network_mode: host

  hasura:
    build: .
    env_file: ./.env
    restart: always
    network_mode: host

volumes:
  db_data:
