apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cnpg-backup-credentials
spec:
  encryptedData:
    azurestorageaccountkey: AgC4w2BCS6fR5YIi5Z0ofKRRE5lGNVlU48EjI6O5tf2quT/hxftXmiIeWnRvOCIGWsRbm/e5i1K0z409tMD6Ms/LuP3f6eF4PbmRlklSEFvl43KhFkgU7gdzZhfh458Gb4QPNMcwdx97wnQRQ/bCwhAR04p4oCIUSZeU4+gv8ru7uY9hw0pFUq8cveZ614neQkfgoTEPsby7/AbkgXUqOnTrz1xDfffytrhiXphl5sG0jyrmBnKrppIbhNEoQD1D/tVY5rN8c+zAnZQWrrvh6M6Y/CY0Ybp2gb+H63pqFQFkPegyIvMb/5lQYDbrGhSiu0BpBcvlXlHXKjzYShk90j7+2HLuYtpijSZZeetNsVJrh98QxVNgHsaTC7nkJKiM6LlxXB7aPRe8XY3ITSH9Y+09Gfa6gxvm1n6wpmBqazgxvnBAzDKuhI8RgLbr76smTfRG2doNdpWzrbakXwezxlClXBL0GPwqKHjvWHvNnrNdG3EvqfSYcktfUCoC7JlTShUp6ccklda4ZJHKoH1PF7UojoloOIYJ34ZCGlllTucCaPhWnd6+hygV7e6tfEG42tQt2HO7gxsQs8jyLhUsKHxDui3IlXeOx7N47kSgtZcr5WrcElkCKSyR0Ap8PY44CEy1J2LoAtkVH9ddF8jVaRIhZRlc3AILgUKP1tM0VmEG01vDFeLj21aNpRoFoQLBJ+9vcVVtTCdB/1soe5NUPIp9CJhyMprk5d9rYGVuRFM5dgrTvHbXGVaNAVYNKaGmSwm86EJGmdWuyPddZt+NdufWEesfFANqOrplOYd+Tk0N21dOarYZDxfL
    azurestorageaccountname: AgC/nozz3c6rTKvH/oJuWrRinl8V6pnrozC5ZzEXxLzpw+TQwNbr3BAqv10fxd0oDFMaSGR63HvxCYbCKHbQ7ZYIuwLguPxhG9CBjuy+Hm8sv7+eZbNfV+/aM3wskeiHmsSf3qnk0jvy6afp+U4n1ZJriCx7/FYM/iyPjO/SKUJ6Fp/wDoIx7FB6u8061F3rCT2bS/xQI6UPVRLe82TMfd0lcXIbShKCq1XtvWD+Pu6bP0dBmumWV2pbK7atfGAwcBwup0FRI/hndGSQhRpGEAJxIh/LTUSFifcWmGDWK9rhzg25WFAEavsuzllDL2pBbj3lTCs5Of/tIiA3skYXBpkBGSSDUA4dVMZA9y+tTjyeck+mjPOOktNtG6tmi95trcYCA5dx7w82o92ggSL0vfbMHLjv2gkiZWNETnfXdyMyyHpU/g+Er+/djx4RBcdnuKaaVVKakixP6hMS1tZIB1PTR0iIliGPRPPzG4DbSrvBDI+p/GQ2Ahs9zjR1AaUcypGP4DP7nl09TUt818YiZHnAt935mrkkF84EoduL81HpXVDXiao1fVDh2h6AkVjmYsY4wI6fDVXXKWaiMH4ZzVJYoa7dP+B6o/FAyfgcq76pCXSvyWD1HTJo4Nm8KT41WIb3hSjO9pqreKGTnkMKakq7kAEvREj2Ycc4uJ2JAazSsRFTKvVsderTU2VgKmCeNLa8sBzQAXtLOcCzFNiH1/Vdh/b1EIjTuQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cnpg-backup-credentials
    type: Opaque
