app:
  replicas: 1

hasura:
  replicas: 1
  envFrom:
    - secretRef:
        name: hasura
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - configMapRef:
        name: hasura-configmap
