components:
  app: true
  hasura: true

app:
  envFrom:
    - secretRef:
        name: app
  probesPath: /healthz
  replicas: 2

hasura:
  envFrom:
    - secretRef:
        name: hasura
    - configMapRef:
        name: hasura-configmap
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  replicas: 2
