apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: hasura
  namespace: secretariat
spec:
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgAeH5++V4FDYH0OVaCdcO4v6tkqBoUwo0IMC8ztuHv7I6+Rjei0sRKa4u5nqkC3vAKYFRG0kpeeDw6/es0e8EKeaOtWnC71rGrAAs7T5v6ZzsL0Q7nHXa+NupFVmk121yzSArBbFPs4F+5bvxADJZOkQaA0o+fwFJ5WHz/2ezmyyyvOPNjl+ckopjBYgqJrTPZt6upII6Skxmr7SMbx5UM2afURsR3PQKPLCcGrSIFpHmIIhzsphTjARsqUhTgWvh1jw19WkcBuIHWVtQmUN0LfrtoyHgM1zT/Lh/rqkg5ZUD/PeBBWKqyyi+ms1ZDbSKEGs7ZVlTz+NFgSFkE9NjTg7LZveZLd2TZqocu22zKdxFkJK78rf+rElRWxTEVHQzwj6/PF1/xPvX0+6WUkvVpKv66xgyWU11aJ2HiOiqNqWZp/dyoKNi73dDpmFQfwiMtXSNhH1uLfn5Z3K4A71q/wKLANAUXVwnITNJPpQcJiHxcynPWCg2bgGZs0y0jrS9RE4oWZY+gMjkDLiD15hzhmQv2nd1vPathJ7ecHHeEtLXaqeXEu53w/9/+Spd6xhgGOWKgJplvh1cPPirtthhxs9vDOvu0z4+JIrCFvm6UEZHC+3FoXRlcQk5AxBRVYbZbkZd6EJNzm9ggPh0gcH5acE+dl22gxc9B/z9H4SI5ayhqsRL9sTbETaGCoSdZpvC3T01sPf98t6qzAH2I+kg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: hasura
    type: Opaque
