name: 🗼 Lighthouse

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: lighthouse-${{ github.event.deployment.environment }}

jobs:
  lhci:
    runs-on: ubuntu-22.04
    name: Run lhci on deployed environment
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run lhci
        run:
          npx --yes @lhci/cli@latest autorun
          --collect.url=https://secretariat-preprod.ovh.fabrique.social.gouv.fr
        env:
          LHCI_GITHUB_APP_TOKEN:
            ${{ secrets.SOCIALGROOVYBOT_LHCI_GITHUB_APP_TOKEN }}
