name: Lighthouse

on: deployment_status

# concurrency:
#   cancel-in-progress: true
#   group: lighthouse-${{ github.event.deployment_status.deployment_id }}

jobs:
  lhci:
    name: Run lhci on deployed environment
    # if: github.event.deployment_status.step == 'finish' && github.event.deployment_status.status == 'success'
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: debug
        run: |
          echo deployment_status: ${{ github.event.deployment_status }}

      - name: debug
        run: |
          echo target_url: ${{ github.event.deployment_status.target_url }}
          echo env_url: ${{ github.event.deployment_status.env_url }}
          echo status: ${{ github.event.deployment_status.status }}
          echo step: ${{ github.event.deployment_status.step }}

      # - name: run lhci
      #   run: npx --yes @lhci/cli@latest autorun --collect.url=${{ github.event.deployment_status.env_url }}
      #   env:
      #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
