name: Lighthouse

on: deployment_status

concurrency:
  cancel-in-progress: true
  group: lighthouse-${{ github.event.deployment.environment }}

jobs:
  lhci:
    runs-on: ubuntu-22.04
    name: Run lhci on deployed environment
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment_url
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run lhci
        run: npx --yes @lhci/cli@latest autorun --collect.url=${{ github.event.deployment_status.environment_url }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.SOCIALGROOVYBOT_LHCI_GITHUB_APP_TOKEN }}
