name: Preproduction

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction-${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER NEXT APP
  ##############################################################################
  register-app:
    name: Build & Register app
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: preprod
          imageName: secretariat/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            NEXT_PUBLIC_HASURA_URL=https://hasura-secretariat-preprod.dev.fabrique.social.gouv.fr/v1/graphql

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: preprod
          dockerfile: ./packages/hasura/Dockerfile
          dockercontext: ./packages/hasura
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: secretariat/hasura

  ##############################################################################
  ## DEPLOY BACKEND
  ##############################################################################
  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    needs: [register-app, register-hasura]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: preprod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
