name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER NEXT APP
  ##############################################################################
  register-app:
    name: Build & Register app
    runs-on: ubuntu-latest
    steps:
      - name: Get commit sha
        run: |
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: prod
          imageName: secretariat/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            GITHUB_SHA=${{ env.GITHUB_SHA }}
            NEXT_PUBLIC_MATOMO_SITE_ID=82
            NEXT_PUBLIC_MATOMO_URL=https://matomo.fabrique.social.gouv.fr/
            NEXT_PUBLIC_HASURA_URL=https://hasura-secretariat.fabrique.social.gouv.fr/v1/graphql

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: prod
          dockerfile: ./packages/hasura/Dockerfile
          dockercontext: ./packages/hasura
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: secretariat/hasura
          dockerbuildargs: |
            APP_URL=https://secretariat.fabrique.social.gouv.fr

  ##############################################################################
  ## DEPLOY BACKEND
  ##############################################################################
  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register-app, register-hasura]
    environment:
      name: production
      url: https://secretariat.fabrique.social.gouv.fr/
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: prod
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
