name: 📦 Release
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get GitHub App Token
        id: token
        uses: SocialGouv/token-bureau@main
        with:
          token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
          audience: socialgouv
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extends: |
            @socialgouv/releaserc
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
