name: Review

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER NEXT APP
  ##############################################################################
  register-app:
    name: Build & Register app
    runs-on: self-hosted
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Get branch slug
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
          echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV

      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            NEXT_PUBLIC_HASURA_URL=https://hasura-secretariat-${{ env.BRANCH_SLUG }}.dev.fabrique.social.gouv.fr/v1/graphql

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: self-hosted
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          dockerfile: ./packages/hasura/Dockerfile
          dockercontext: ./packages/hasura
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: ${{ env.project }}/hasura

  ##############################################################################
  ## GENERATE KUBERNETES MANIFESTS
  ##############################################################################
  manifests:
    name: Generate k8s manifests
    runs-on: self-hosted
    steps:
      - name: Use autodevops manifests generation
        uses: SocialGouv/actions/autodevops-manifests@v1
        with:
          environment: 'dev'
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## DEPLOY
  ##############################################################################
  deploy:
    name: Deploy review branch
    runs-on: self-hosted
    needs: [register-app, register-hasura, manifests]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@yq-no-action
        with:
          environment: 'dev'
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
