name: Review

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER APP IMAGE
  ##############################################################################
  register-backend:
    name: Build & Register backend
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/backend
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./packages/backend/Dockerfile
          dockercontext: ./packages/backend

  register-frontend:
    name: Build & Register frontend
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./packages/frontend/Dockerfile
          dockercontext: ./packages/frontend

  ##############################################################################
  ## GENERATE KUBERNETES MANIFESTS
  ##############################################################################
  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: 'dev'
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  ##############################################################################
  ## DEPLOY BACKEND
  ##############################################################################
  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    needs: [register-backend, register-frontend, manifests]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: 'dev'
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}