name: Review

on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  ##############################################################################
  ## CREATE POSTGRES DATABASE
  ##############################################################################
  create-db:
    name: Create postgres database
    runs-on: self-hosted
    steps:

    - uses: SocialGouv/actions/autodevops-create-db@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}

  ##############################################################################
  ## BUILD AND REGISTER NEXT APP
  ##############################################################################
  register-app:
    name: Build & Register app
    runs-on: self-hosted
    steps:
      - name: Get branch slug
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
          echo "BRANCH_SLUG=${BRANCH_SLUG}" >> $GITHUB_ENV

      - name: Debug SHA
        run: |
          echo GITHUB_SHA_1 ${{ env.GITHUB_SHA }}
          echo GITHUB_SHA_2 ${GITHUB_SHA}

      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imageName: secretariat/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            GITHUB_SHA=$GITHUB_SHA
            GITHUB_SHA_2=${{ env.GITHUB_SHA }}
            NEXT_PUBLIC_HASURA_URL=https://hasura-secretariat-${{ env.BRANCH_SLUG }}.dev.fabrique.social.gouv.fr/v1/graphql
        env:
          GITHUB_SHA: ${{ env.GITHUB_SHA }}

  ##############################################################################
  ## BUILD AND REGISTER HASURA IMAGE
  ##############################################################################
  register-hasura:
    name: Build & Register Hasura
    runs-on: self-hosted
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          dockerfile: ./packages/hasura/Dockerfile
          dockercontext: ./packages/hasura
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: secretariat/hasura

  ##############################################################################
  ## DEPLOY
  ##############################################################################
  deploy:
    name: Deploy review branch
    runs-on: self-hosted
    needs: [register-app, register-hasura, create-db]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: 'dev'
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
