name: Tests

on:
  push:
    branches-ignore:
      - 'master'

concurrency:
  cancel-in-progress: true
  group: tests-${{ github.ref }}

jobs:

  ##############################################################################
  ## TEST APPLICATION
  ##############################################################################
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Node setup
      uses: actions/setup-node@v2
      with:
        node-version: '16.13'

    - name: Yarn cache setup
      uses: c-hive/gha-yarn-cache@v1

    - name: Install dependencies
      run: yarn --frozen-lockfile --prefer-offline

    - name: Run tests
      run: yarn test --coverage

    # - name: Publish code coverage
    #   uses: codecov/codecov-action@v2
    #   with:
    #     fail_ci_if_error: true
    #     token: ${{ secrets.CODECOV_TOKEN }}

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
